# This rule is not used by the project opea-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the opea-operator.opea.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opea-operator
    app.kubernetes.io/managed-by: kustomize
  name: opeacache-editor-role
rules:
- apiGroups:
  - opea-operator.opea.io
  resources:
  - opeacaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opea-operator.opea.io
  resources:
  - opeacaches/status
  verbs:
  - get
