---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opea-operator.opea.io
  resources:
  - opeacaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opea-operator.opea.io
  resources:
  - opeacaches/finalizers
  verbs:
  - update
- apiGroups:
  - opea-operator.opea.io
  resources:
  - opeacaches/status
  verbs:
  - get
  - patch
  - update
