---
apiVersion: opea-operator.opea.io/v1alpha1
kind: OpeaCache
metadata:
  labels:
    app.kubernetes.io/name: opea-operator
    app.kubernetes.io/managed-by: kustomize
  name: chatqna-models
  namespace: opea-worker
spec:
  sources:
    - from: huggingface
      params:
        - name: repoId
          value: BAAI/bge-base-en-v1.5
        - name: repoType
          value: model
        - name: revision
          value: latest
        - name: token
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_token
  storage:
    pvc:
      subPath: "demo/"
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
  jobConf:
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
      - name: env_for_test
        value: http://proxy-us.intel.com:912

---
apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: opea-worker
type: Opaque
data:
  hf_token: "aGZfRkNtUk5PRWJrblRSTXd0RmdydlN6RE9FYk5WSmlUU2ZUQw=="
