apiVersion: opea-operator.opea.io/v1alpha1
kind: OpeaCache
metadata:
  labels:
    app.kubernetes.io/name: opea-operator
    app.kubernetes.io/managed-by: kustomize
  name: opeacache-sample
spec:
  source:
    huggingFace:
      repoId: Intel/neural-chat-7b-v3-3
      repoType: model
      revision: latest`
      token: ""
  storage:
    pvc:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: local-path



